//
// Created by ukasz on 20.04.2023.
//

#ifndef CURRENCYRATES_CURRENCIES_H
#define CURRENCYRATES_CURRENCIES_H
#define EUR "EUR"
#define USD "USD"
#define CURRENCIES EUR, USD
#endif //CURRENCYRATES_CURRENCIES_H
